---
- hosts: openshift-master
  become: yes
  become_method: sudo
  vars_files:
      - group_vars/all

  roles:
    - common
    - create_hello_world
    - scale_hello_world
    - expose_route_hello_world
    - destroy_hello_world
