---
 - name: Fetch json openshift template
   template:
       src: hello-pod.j2
       dest: "{{ json_path }}"

 - name: Create new helloworld app
   command: oc create -f {{ json_path }} {{ post_args }}
